/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CabinsIndexRouteImport } from './routes/cabins.index'
import { Route as CabinsCabinIdRouteImport } from './routes/cabins.$cabinId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsIndexRoute = CabinsIndexRouteImport.update({
  id: '/cabins/',
  path: '/cabins/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsCabinIdRoute = CabinsCabinIdRouteImport.update({
  id: '/cabins/$cabinId',
  path: '/cabins/$cabinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/cabins/$cabinId': typeof CabinsCabinIdRoute
  '/cabins/': typeof CabinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/cabins/$cabinId': typeof CabinsCabinIdRoute
  '/cabins': typeof CabinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/cabins/$cabinId': typeof CabinsCabinIdRoute
  '/cabins/': typeof CabinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gallery' | '/cabins/$cabinId' | '/cabins/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/cabins/$cabinId' | '/cabins'
  id: '__root__' | '/' | '/gallery' | '/cabins/$cabinId' | '/cabins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  CabinsCabinIdRoute: typeof CabinsCabinIdRoute
  CabinsIndexRoute: typeof CabinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins/': {
      id: '/cabins/'
      path: '/cabins'
      fullPath: '/cabins/'
      preLoaderRoute: typeof CabinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins/$cabinId': {
      id: '/cabins/$cabinId'
      path: '/cabins/$cabinId'
      fullPath: '/cabins/$cabinId'
      preLoaderRoute: typeof CabinsCabinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  CabinsCabinIdRoute: CabinsCabinIdRoute,
  CabinsIndexRoute: CabinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
